version: '3'

services:
  openldap:
    container_name: ldap_node_express
    image: docker.io/bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    env_file:
      - .env
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_USERS=user01,user02
    networks:
      - open_ldap_network
    volumes:
      - open_ldap_data:/bitnami/openldap

networks:
  open_ldap_network:
    name: nw_ldap_node_express
    driver: bridge

volumes:
  open_ldap_data:
    name: vol_ldap_node_express
    driver: local
